version: '3.4'

services:
  TranslateBot:
    image: translateimg
    container_name: translatebot
    build:
      context: .
      dockerfile: Dockerfile
      args:
        tokemBot: ${TOKEN}
    networks:
      - tral
    depends_on:
      - database

  database:
    image: mysql
    container_name: translatebotbase
    command: --default-authentication-plugin=mysql_native_password
    restart: always
    environment:
      MYSQL_DATABASE: 'db'
      # So you don't have to use root, but you can if you like
      MYSQL_USER: 'user'
      # You can use whatever password you like
      MYSQL_PASSWORD: 'password'
      # Password for root access
      MYSQL_ROOT_PASSWORD: 'password'

      # Where our data will be persisted
    volumes:
      - ./db/init.sql:/docker-entrypoint-initdb.d/init.sql
      - /root/repo/bacupTranslate/:/var/lib/mysql/ # Backup folder in host mapped to backup 
    networks:
      - tral


volumes:
  my-db:
networks:
  tral:
    driver: bridge